esphome:
  name: toad-lights
  comment: Toad lights

external_components:
  # - source: github://luar123/zigbee_esphome
  #   components: [zigbee]
  
  - source: github://simmsb/zigbee_esphome
    components: [zigbee]

  - source: github://pr#7942
    refresh: 1h
    components:
      - adc

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    # version: latest
    # sdkconfig_options:
    #   CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

    version: '5.3.1'
    platform_version: '6.9.0'
    # source: |-
    #   https://github.com/tasmota/esp-idf/releases/download/v5.1.3.240313/esp-idf-v5.1.3.zip
    sdkconfig_options: 
      CONFIG_ZB_ENABLED: y
      CONFIG_ZB_ZED: y
      CONFIG_ZB_RADIO_NATIVE: y
      ZB_ED_ROLE: y

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
#   hardware_uart: UART0

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: "temp"
    filters:
      - delta: 0.1

  - platform: adc
    id: battery_percentage
    name: "Battery percentage"
    pin: 0
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: 12dB
    samples: 10
    filters:
      - multiply: 2.0  # The voltage divider requires us to multiply by 2
      - calibrate_linear:
         method: exact
         datapoints:
          - 0.00 -> 0.0
          - 3.30 -> 1.0
          - 3.39 -> 10.0
          - 3.75 -> 50.0
          - 4.11 -> 90.0
          - 4.20 -> 100.0
      - lambda: |-
          if (x <= 100) {
            return x;
          } else {
            return 100;
          }
          if (x <0) {
            return 0;
          }
zigbee:
  id: "zb"
  endpoints:
    - num: 1
      device_type: DIMMABLE_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              on_value:
                then:
                  - light.control:
                      id: light_1
                      state: !lambda "return (bool)x;"
                  - light.control:
                      id: light_status
                      state: !lambda "return (bool)x;"
        - id: LEVEL_CONTROL
          attributes:
            - attribute_id: 0
              type: U8
              on_value:
                then:
                  - light.control:
                      id: light_1
                      brightness: !lambda "return ((float)x)/255;"
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temp
              scale: 100
        - id: POWER_CONFIG
          attributes:
            # https://github.com/espressif/esp-zigbee-sdk/blob/a943a91/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_power_config.h
            - attribute_id: 0x0021 # ESP_ZB_ZCL_ATTR_POWER_CONFIG_BATTERY_PERCENTAGE_REMAINING_ID
              type: u8
              report: true
              device: battery_percentage
              lambda: !lambda "return x * (200.0 / 100.0);"
            - attribute_id: 0x0031 # ESP_ZB_ZCL_ATTR_POWER_CONFIG_BATTERY_SIZE_ID
              type: u8
              value: 0x1 # ESP_ZB_ZCL_POWER_CONFIG_BATTERY_SIZE_BUILT_IN
              
  on_join:
    then:
      - logger.log: "Joined network"

light:
  - platform: binary
    output: light_status_gpio
    id: light_status

  - platform: monochromatic
    output: boost_on
    id: light_1
    on_turn_on:
      - output.turn_on:
          id: fet_on
    on_turn_off:
      - output.turn_off:
          id: fet_on

output:
  - platform: gpio
    pin: 15
    id: light_status_gpio
  - platform: gpio
    pin: 16
    id: fet_on
  - platform: ledc
    pin: 17
    id: boost_on 
    frequency: "10khz"
    max_power: "45%"

binary_sensor:
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb
